// Code generated by entc, DO NOT EDIT.

package vote

import (
	"foodly/ent/predicate"

	"github.com/facebook/ent/dialect/sql"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatus), v))
	})
}

// Restaurant applies equality check predicate on the "restaurant" field. It's identical to RestaurantEQ.
func Restaurant(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRestaurant), v))
	})
}

// Food applies equality check predicate on the "food" field. It's identical to FoodEQ.
func Food(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFood), v))
	})
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUsername), v))
	})
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatus), v))
	})
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStatus), v))
	})
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Vote {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Vote(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStatus), v...))
	})
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Vote {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Vote(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStatus), v...))
	})
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStatus), v))
	})
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStatus), v))
	})
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStatus), v))
	})
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStatus), v))
	})
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldStatus), v))
	})
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldStatus), v))
	})
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldStatus), v))
	})
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldStatus), v))
	})
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldStatus), v))
	})
}

// RestaurantEQ applies the EQ predicate on the "restaurant" field.
func RestaurantEQ(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRestaurant), v))
	})
}

// RestaurantNEQ applies the NEQ predicate on the "restaurant" field.
func RestaurantNEQ(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldRestaurant), v))
	})
}

// RestaurantIn applies the In predicate on the "restaurant" field.
func RestaurantIn(vs ...string) predicate.Vote {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Vote(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldRestaurant), v...))
	})
}

// RestaurantNotIn applies the NotIn predicate on the "restaurant" field.
func RestaurantNotIn(vs ...string) predicate.Vote {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Vote(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldRestaurant), v...))
	})
}

// RestaurantGT applies the GT predicate on the "restaurant" field.
func RestaurantGT(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldRestaurant), v))
	})
}

// RestaurantGTE applies the GTE predicate on the "restaurant" field.
func RestaurantGTE(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldRestaurant), v))
	})
}

// RestaurantLT applies the LT predicate on the "restaurant" field.
func RestaurantLT(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldRestaurant), v))
	})
}

// RestaurantLTE applies the LTE predicate on the "restaurant" field.
func RestaurantLTE(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldRestaurant), v))
	})
}

// RestaurantContains applies the Contains predicate on the "restaurant" field.
func RestaurantContains(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldRestaurant), v))
	})
}

// RestaurantHasPrefix applies the HasPrefix predicate on the "restaurant" field.
func RestaurantHasPrefix(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldRestaurant), v))
	})
}

// RestaurantHasSuffix applies the HasSuffix predicate on the "restaurant" field.
func RestaurantHasSuffix(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldRestaurant), v))
	})
}

// RestaurantEqualFold applies the EqualFold predicate on the "restaurant" field.
func RestaurantEqualFold(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldRestaurant), v))
	})
}

// RestaurantContainsFold applies the ContainsFold predicate on the "restaurant" field.
func RestaurantContainsFold(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldRestaurant), v))
	})
}

// FoodEQ applies the EQ predicate on the "food" field.
func FoodEQ(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFood), v))
	})
}

// FoodNEQ applies the NEQ predicate on the "food" field.
func FoodNEQ(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldFood), v))
	})
}

// FoodIn applies the In predicate on the "food" field.
func FoodIn(vs ...string) predicate.Vote {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Vote(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldFood), v...))
	})
}

// FoodNotIn applies the NotIn predicate on the "food" field.
func FoodNotIn(vs ...string) predicate.Vote {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Vote(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldFood), v...))
	})
}

// FoodGT applies the GT predicate on the "food" field.
func FoodGT(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldFood), v))
	})
}

// FoodGTE applies the GTE predicate on the "food" field.
func FoodGTE(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldFood), v))
	})
}

// FoodLT applies the LT predicate on the "food" field.
func FoodLT(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldFood), v))
	})
}

// FoodLTE applies the LTE predicate on the "food" field.
func FoodLTE(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldFood), v))
	})
}

// FoodContains applies the Contains predicate on the "food" field.
func FoodContains(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldFood), v))
	})
}

// FoodHasPrefix applies the HasPrefix predicate on the "food" field.
func FoodHasPrefix(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldFood), v))
	})
}

// FoodHasSuffix applies the HasSuffix predicate on the "food" field.
func FoodHasSuffix(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldFood), v))
	})
}

// FoodEqualFold applies the EqualFold predicate on the "food" field.
func FoodEqualFold(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldFood), v))
	})
}

// FoodContainsFold applies the ContainsFold predicate on the "food" field.
func FoodContainsFold(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldFood), v))
	})
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUsername), v))
	})
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUsername), v))
	})
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.Vote {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Vote(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUsername), v...))
	})
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.Vote {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Vote(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUsername), v...))
	})
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUsername), v))
	})
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUsername), v))
	})
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUsername), v))
	})
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUsername), v))
	})
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldUsername), v))
	})
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldUsername), v))
	})
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldUsername), v))
	})
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldUsername), v))
	})
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldUsername), v))
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Vote) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Vote) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Vote) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		p(s.Not())
	})
}
