// Code generated by entc, DO NOT EDIT.

package food

const (
	// Label holds the string label denoting the food type in the database.
	Label = "food"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldRestaurant holds the string denoting the restaurant field in the database.
	FieldRestaurant = "restaurant"
	// FieldDesc holds the string denoting the desc field in the database.
	FieldDesc = "desc"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldImageName holds the string denoting the image_name field in the database.
	FieldImageName = "image_name"

	// Table holds the table name of the food in the database.
	Table = "foods"
)

// Columns holds all SQL columns for food fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldRestaurant,
	FieldDesc,
	FieldPrice,
	FieldImageName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
