// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"foodly/ent/vote"
	"strings"

	"github.com/facebook/ent/dialect/sql"
)

// Vote is the model entity for the Vote schema.
type Vote struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Restaurant holds the value of the "restaurant" field.
	Restaurant string `json:"restaurant,omitempty"`
	// Food holds the value of the "food" field.
	Food string `json:"food,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Vote) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // status
		&sql.NullString{}, // restaurant
		&sql.NullString{}, // food
		&sql.NullString{}, // username
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Vote fields.
func (v *Vote) assignValues(values ...interface{}) error {
	if m, n := len(values), len(vote.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	v.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field status", values[0])
	} else if value.Valid {
		v.Status = value.String
	}
	if value, ok := values[1].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field restaurant", values[1])
	} else if value.Valid {
		v.Restaurant = value.String
	}
	if value, ok := values[2].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field food", values[2])
	} else if value.Valid {
		v.Food = value.String
	}
	if value, ok := values[3].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field username", values[3])
	} else if value.Valid {
		v.Username = value.String
	}
	return nil
}

// Update returns a builder for updating this Vote.
// Note that, you need to call Vote.Unwrap() before calling this method, if this Vote
// was returned from a transaction, and the transaction was committed or rolled back.
func (v *Vote) Update() *VoteUpdateOne {
	return (&VoteClient{config: v.config}).UpdateOne(v)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (v *Vote) Unwrap() *Vote {
	tx, ok := v.config.driver.(*txDriver)
	if !ok {
		panic("ent: Vote is not a transactional entity")
	}
	v.config.driver = tx.drv
	return v
}

// String implements the fmt.Stringer.
func (v *Vote) String() string {
	var builder strings.Builder
	builder.WriteString("Vote(")
	builder.WriteString(fmt.Sprintf("id=%v", v.ID))
	builder.WriteString(", status=")
	builder.WriteString(v.Status)
	builder.WriteString(", restaurant=")
	builder.WriteString(v.Restaurant)
	builder.WriteString(", food=")
	builder.WriteString(v.Food)
	builder.WriteString(", username=")
	builder.WriteString(v.Username)
	builder.WriteByte(')')
	return builder.String()
}

// Votes is a parsable slice of Vote.
type Votes []*Vote

func (v Votes) config(cfg config) {
	for _i := range v {
		v[_i].config = cfg
	}
}
