// Code generated by entc, DO NOT EDIT.

package comment

const (
	// Label holds the string label denoting the comment type in the database.
	Label = "comment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFood holds the string denoting the food field in the database.
	FieldFood = "food"
	// FieldRestaurant holds the string denoting the restaurant field in the database.
	FieldRestaurant = "restaurant"
	// FieldMsg holds the string denoting the msg field in the database.
	FieldMsg = "msg"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"

	// Table holds the table name of the comment in the database.
	Table = "comments"
)

// Columns holds all SQL columns for comment fields.
var Columns = []string{
	FieldID,
	FieldFood,
	FieldRestaurant,
	FieldMsg,
	FieldUsername,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
